name: gatsby-auth-webops

proxy:
  appserver:
    - gatsby-auth-webops.lndo.site

services:
  appserver:
    type: "node:10"
    globals:
      gatsby-cli: latest
      firebase-tools: latest
    build:
      - "yarn install"
    command:
      - "gatsby develop --host 0.0.0.0 --port 80"

tooling:
  firebase:
    service: appserver
  yarn:
    service: appserver
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: appserver
  gatsby:
    service: appserver
  gatsby:start:
    cmd: gatsby develop --host 0.0.0.0 --port 80
    service: appserver